name: Build application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installation python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Flask
      run: |
         python -m pip install flask


